### PR TITLE
code review

### PR DESCRIPTION
**Pull request by atenaiis**
Team,

The aim of this project is to build a library where  all of your book objects are going to be stored in a simple array, 
adding a form to add books and button to remove it or mark it as read.

Please follow the Read me file instructions to taste it.

Cheers.

Mariana A. Campos

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
#### Changes Required! :recycle: 
Nicely done @atenaiis! :+1: I like your use of the IIFE to encapsulate most of your Book's features! :ok_hand: There are just a few suggestions I have for you. These include:
- [x] The form should allow a user to mark the `Book` status as `read`. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/new_book_button_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))
- [ ] __[Optional]__ Add data persistence by saving, retrieving, and updating the library books using [the localstorage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/localstorage_stretch_requirement.png) from [Odin Project](https://www.theodinproject.com/courses/javascript/lessons/library))

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__[Treasure Kabareebe](https://trekab.github.io)__

**Comment by atenaiis** [comment]
thanks for that quick review.

It actually allows you to mark the book as read if you click on **"mark as read"**
thank you 

Cheers!

**Comment by trekab** [comment]
Yes, @atenaiis. I saw where you implemented that on the created books. :+1: However, the requirements expect you to give the user this option from the form i.e. on book creation. For your current implementation, the user only gets access to the book's status __after__ creating it. :thinking:

**Comment by atenaiis** [comment]
Thanks for pointing that out

I've implemented the checkbox for this.

thank you

**Review by rindrajosia — APPROVED** [review]
Approved! :tada:
Congratulations are in order. :clap: Keep up the good work!
You may merge :+1: :+1:

All the best on your next projects! :wink:

**Pull request merged**
